[package]
name = "rss-feed"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
constcat = "0.5.0"
quick-xml = "0.36.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
